export const ALL_ORDERS_REQUEST = "ALL_ORDERS_REQUEST"
export const ALL_ORDERS_SUCCESS = "ALL_ORDERS_SUCCESS"
export const ALL_ORDERS_FAIL = "ALL_ORDERS_FAIL"

export const TODAY_ORDERS_REQUEST = "TODAY_ORDERS_REQUEST"
export const TODAY_ORDERS_SUCCESS = "TODAY_ORDERS_SUCCESS"
export const TODAY_ORDERS_FAIL = "TODAY_ORDERS_FAIL"


export const USER_ORDERS_REQUEST = "USER_ORDERS_REQUEST"
export const USER_ORDERS_SUCCESS = "USER_ORDERS_SUCCESS"
export const USER_ORDERS_FAIL = "USER_ORDERS_FAIL"

export const GET_ORDER_REQUEST = "GET_ORDER_REQUEST"
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS"
export const GET_ORDER_FAIL = "GET_ORDER_FAIL"


export const GET_SHIPPING_INFO_REQUEST = "GET_USER_SHIPPING_INFO"
export const GET_SHIPPING_INFO_SUCCESS = "GET_SHIPPING_INFO_SUCCESS"
export const GET_SHIPPING_INFO_FAIL = "GET_SHIPPING_INFO_FAIL"


export const UDPATE_ORDER_REQUEST = "UDPATE_ORDER_REQUEST"
export const UDPATE_ORDER_SUCCESS = "UDPATE_ORDER_SUCCESS"
export const UDPATE_ORDER_FAIL = "UDPATE_ORDER_FAIL"
export const UDPATE_ORDER_RESET = "UDPATE_ORDER_RESET"

export const CREATE_INVOICE_REQUEST = "CREATE_INVOICE_REQUEST"
export const CREATE_INVOICE_SUCCESS = "CREATE_INVOICE_SUCCESS"
export const CREATE_INVOICE_FAIL = "CREATE_INVOICE_FAIL"

export const GET_INVOICE_REQUEST = "GET_INVOICE_REQUEST"
export const GET_INVOICE_SUCCESS = "GET_INVOICE_SUCCESS"
export const GET_INVOICE_FAIL = "GET_INVOICE_FAIL"

export const GET_ALL_INVOICE_REQUEST = "GET_ALL_INVOICE_REQUEST"
export const GET_ALL_INVOICE_SUCCESS = "GET_ALL_INVOICE_SUCCESS"
export const GET_ALL_INVOICE_FAIL = "GET_ALL_INVOICE_FAIL"




export const CLEAR_ERRORS = "CLEAR_ERRORS"