export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";

export const ADMIN_PRODUCT_REQUEST = "ADMIN_PRODUCT_REQUEST";
export const ADMIN_PRODUCT_SUCCESS = "ADMINL_PRODUCT_SUCCESS";
export const ADMIN_PRODUCT_FAIL = "ADMIN_PRODUCT_FAIL";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST"
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS"
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL"
export const DELETE_PRODUCT_RESET = "DELETE_PRODUCT_RESET"

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const NEW_PRODUCT_REQUEST = "NEW_PRODUCT_REQUEST"
export const NEW_PRODUCT_SUCCESS = "NEW_PRODUCT_SUCCESS"
export const NEW_PRODUCT_FAIL = "NEW_PRODUCT_FAIL"
export const NEW_PRODUCT_RESET = "NEW_PRODUCT_RESET"

export const NEW_BRAND_REQUEST = "NEW_BRAND_REQUEST"
export const NEW_BRAND_SUCCESS = "NEW_BRAND_SUCCESS"
export const NEW_BRAND_FAIL = "NEW_BRAND_FAIL"
export const NEW_BRAND_RESET = "NEW_BRAND_RESET"

export const ALL_BRANDS_REQUEST = "ALL_BRANDS_REQUEST";
export const ALL_BRANDS_SUCCESS = "ALL_BRANDS_SUCCESS";
export const ALL_BRANDS_FAIL = "ALL_BRANDS_FAIL";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "AUPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";
export const UPDATE_PRODUCT_RESET = "UPDATE_PRODUCT_RESET";

export const SAVE_VARIANT_INFO = 'SAVE_VARIANT_INFO';
export const SAVE_VARIANT_SUCCESS = 'SAVE_VARIANT_SUCCESS';
export const SAVE_VARIANT_FAIL = 'SAVE_VARIANT_FAIL';
export const SAVE_VARIANT_RESET = 'SAVE_VARIANT_RESET';

export const ADD_OPTIONS = 'ADD_OPTIONS';
export const ADD_VARIANT = 'ADD_VARAINT';
export const REMOVE_OPTION = 'REMOVE_OPTION';
export const LOCAL_RESET = 'LOCAL_RESET';

export const GET_DISCOUNT_REQUEST = "GET_DISCOUNT_REQUEST"
export const GET_DISCOUNT_SUCCESS = "GET_DISCOUNT_SUCCESS"
export const GET_DISCOUNT_FAIL = "GET_DISCOUNT_FAIL"
export const GET_DISCOUNT_RESET = "GET_DISCOUNT_RESET"

export const GET_BRANDS_REQUEST = "GET_BRANDS_REQUEST"
export const GET_BRANDS_SUCCESS = "GET_BRANDS_SUCCESS"
export const GET_BRANDS_FAIL = "GET_BRANDS_FAIL"
export const GET_BRANDS_RESET = "GET_BRANDS_RESET"

export const GET_BRAND_DETAIL_REQUEST = "GET_BRAND_DETAIL_REQUEST"
export const GET_BRAND_DETAIL_SUCCESS = "GET_BRAND_DETAIL_SUCCESS"
export const GET_BRAND_DETAIL_FAIL = "GET_BRAND_DETAIL_FAIL"

export const GET_BRAND_PRODUCT_REQUEST = "GET_BRAND_PRODUCT_REQUEST"
export const GET_BRAND_PRODUCT_SUCCESS = "GET_BRAND_PRODUCT_SUCCESS"
export const GET_BRAND_PRODUCT_FAIL = "GET_BRAND_PRODUCT_FAIL"
export const GET_BRAND_DETAIL_RESET = "GET_BRAND_DETAIL_RESET"

export const CREATE_DISCOUNT_REQUEST = "CREATE_DISCOUNT_REQUEST"
export const CREATE_DISCOUNT_SUCCESS = "CREATE_DISCOUNT_SUCCESS"
export const CREATE_DISCOUNT_FAIL = "CREATE_DISCOUNT_FAIL"
export const CREATE_DISCOUNT_RESET = "CREATE_DISCOUNT_RESET"





export const CLEAR_ERRORS = "CLEAR_ERRORS"