export const GET_STORE_DETAIL_REQUEST = "GET_STORE_DETAIL_REQUEST";
export const GET_STORE_DETAIL_SUCCESS = "GET_STORE_DETAIL_SUCCESS";
export const GET_STORE_DETAIL_FAIL = "GET_STORE_DETAIL_FAIL";

export const DASHBOARD_DETAIL_REQUEST = "DASHBOARD_DETAIL_REQUEST";
export const DASHBOARD_DETAIL_SUCCESS = "DASHBOARD_DETAIL_SUCCESS";
export const DASHBOARD_DETAIL_FAIL = "DASHBOARD_DETAIL_FAIL";



export const CLEAR_ERRORS = "CLEAR_ERRORS"
